lib/profilex/web/router.ex
defmodule Profilex.Web.Router do
  use Profilex.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Profilex.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/signup", RegistrationController, :new
    post "/signup", RegistrationController, :create
    get "/signin", SessionController, :new
    post "/signin", SessionController, :create

    resources "/accounts", AccountController
  end
end

lib/profilex/web/controllers/account_controller.ex
defmodule Profilex.Web.AccountController do
  use Profilex.Web, :controller

  alias Profilex.User

  def index(conn, _params) do
    accounts = User.list_accounts()
    render(conn, "index.html", accounts: accounts)
  end

  def show(conn, %{"id" => id}) do
    account = User.get_account!(id)
    render(conn, "show.html", account: account)
  end

  def edit(conn, %{"id" => id}) do
    account = User.get_account!(id)

    case edit_account(conn, account) do
      {:ok, account, changeset} ->
        render(conn, "edit.html", account: account, changeset: changeset)
      {:error, error} ->
        redirect(conn, to: "/")
    end
  end

  def update(conn, %{"id" => id, "account" => account_params}) do
    account = User.get_account!(id)

    case update_account(conn, account, account_params) do
      {:ok, account} ->
        conn
        |> put_flash(:info, "Account updated successfully.")
        |> redirect(to: account_path(conn, :show, account))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", account: account, changeset: changeset)
      {:error, error_type} ->
        redirect(conn, to: "/")
    end
  end

  def delete(conn, %{"id" => id}) do
    account = User.get_account!(id)

    case delete_account(conn, account) do
      :ok ->
        conn
        |> put_flash(:info, "Account deleted successfully.")
        |> redirect(to: account_path(conn, :index))
      {:error, error_type} ->
        redirect(conn, to: "/")
    end
  end

  defp edit_account(conn, account) do
    current_user = get_session(conn, :current_user)

    case Profilex.User.Auth.can(:edit_account, current_user, account) do
      :ok ->
        account_changeset = User.change_account(account)
        {:ok, current_user, account_changeset}
      {:error, error_type} ->
        {:error, error_type}
    end
  end

  defp update_account(conn, account, account_params) do
    current_user = get_session(conn, :current_user)

    case Profilex.User.Auth.can(:update_account, current_user, account) do
      :ok ->
        case User.update_account(account, account_params) do
          {:ok, account} -> {:ok, account}
          {:error, changeset} -> {:error, changeset}
        end
      {:error, error_type} ->
        {:error, error_type}
    end
  end

  defp delete_account(conn, account) do
    current_user = get_session(conn, :current_user)

    case Profilex.User.Auth.can(:delete_account, current_user, account) do
      :ok ->
        case User.delete_account(account) do
          {:ok, _account} -> :ok
          {:error, changeset} -> {:error, changeset}
        end
      {:error, error_type} ->
        {:error, error_type}
    end
  end
end

lib/profilex/web/controllers/page_controller.ex
defmodule Profilex.Web.PageController do
  use Profilex.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/profilex/web/controllers/registration_controller.ex
defmodule Profilex.Web.RegistrationController do
  use Profilex.Web, :controller

  alias Profilex.User

  def new(conn, _params) do
    changeset = User.prepare_registration(%Profilex.User.Registration{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"registration" => account_params}) do
    case User.register_account(account_params) do
      {:ok, account} ->
        successful_account_creation(conn, account)
      {:error, %Ecto.Changeset{} = changeset} ->
        failed_account_creation(conn, changeset)
    end
  end

  defp successful_account_creation(conn, account) do
    conn
    |> put_flash(:info, "Account created successfully.")
    |> redirect(to: account_path(conn, :show, account))
  end

  defp failed_account_creation(conn, changeset_with_errors) do
    conn
    |> render("new.html", changeset: changeset_with_errors)
  end
end

lib/profilex/web/controllers/session_controller.ex
defmodule Profilex.Web.SessionController do
  use Profilex.Web, :controller

  alias Profilex.User

  def new(conn, _params) do
    changeset = User.prepare_session(%User.Session{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"session" => session_params}) do
    case User.signin_account(session_params) do
      {:ok, account} ->
        conn
        |> put_session(:current_user, account)
        |> put_flash(:info, "Signed in successfully")
        |> redirect(to: account_path(conn, :show, account))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/profilex/web/views/account_view.ex
defmodule Profilex.Web.AccountView do
  use Profilex.Web, :view
end

lib/profilex/web/views/error_view.ex
defmodule Profilex.Web.ErrorView do
  use Profilex.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/profilex/web/views/layout_view.ex
defmodule Profilex.Web.LayoutView do
  use Profilex.Web, :view
end

lib/profilex/web/views/page_view.ex
defmodule Profilex.Web.PageView do
  use Profilex.Web, :view
end

lib/profilex/web/views/registration_view.ex
defmodule Profilex.Web.RegistrationView do
  use Profilex.Web, :view
end

lib/profilex/web/views/session_view.ex
defmodule Profilex.Web.SessionView do
  use Profilex.Web, :view
end

lib/profilex/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Profilex!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><%= link "Sign In", to: session_path(@conn, :new) %></li>
            <li><%= link "Sign Up", to: registration_path(@conn, :new) %></li>
          </ul>
        </nav>
        <%= link to: "/" do %>
          <span class="logo"></span>
        <% end %>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/profilex/web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/profilex/web/templates/session/new.html.eex
<h1>Sign In</h1>

<%= form_for @changeset, session_path(@conn, :create), fn f -> %>
  <%= unless Enum.empty?(f.errors) do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong!</p>
    </div>
  <% end %>

  <div class="form-group">
    <label for="session_email">Email</label>
    <%= email_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <label for="session_password">Password</label>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Sign In", class: "btn btn-primary" %>
  </div>
<% end %>